import Foundation
import SwiftLocalizedGeneratorCore

#if os(macOS)
@main
struct SwiftLocalizedGenerator {
    static func main() throws {
        let arguments = try Arguments(CommandLine.arguments)

        if let input = arguments.input {
            let generatedSource = try generateSymbols(
                for: input,
                temporaryRoot: arguments.output.deletingLastPathComponent()
            )
            let table = input.deletingPathExtension().lastPathComponent
            let publicSource = try LocalizationSymbolTransformer().transform(
                generatedSource,
                table: table,
                namespace: arguments.namespace
            )
            try writeIfChanged(publicSource, to: arguments.output)
        } else {
            try writeIfChanged(
                namespaceSource(named: arguments.namespace),
                to: arguments.output
            )
        }
    }

    private static func namespaceSource(named namespace: String) -> String {
        """
        // Generated by SwiftLocalizedGenerator. Do not edit.

        /// Namespace for type-safe localized resources generated from this target's String Catalogs.
        public enum \(namespace) {}

        """
    }

    private static func generateSymbols(
        for input: URL,
        temporaryRoot: URL
    ) throws -> String {
        let fileManager = FileManager.default
        try fileManager.createDirectory(
            at: temporaryRoot,
            withIntermediateDirectories: true
        )
        let temporaryDirectory = temporaryRoot.appending(
            path: ".swift-localized-generator-\(UUID().uuidString)",
            directoryHint: .isDirectory
        )
        try fileManager.createDirectory(
            at: temporaryDirectory,
            withIntermediateDirectories: true
        )
        defer { try? fileManager.removeItem(at: temporaryDirectory) }

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/xcrun")
        process.arguments = [
            "xcstringstool",
            "generate-symbols",
            input.path,
            "--output-directory",
            temporaryDirectory.path,
            "--language",
            "swift"
        ]
        process.standardError = FileHandle.standardError

        try process.run()
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            throw CodegenError.xcstringstoolFailed(
                status: process.terminationStatus
            )
        }

        let generatedFiles = try fileManager
            .contentsOfDirectory(
                at: temporaryDirectory,
                includingPropertiesForKeys: nil
            )
            .filter { $0.pathExtension == "swift" }

        guard generatedFiles.count == 1,
              let generatedFile = generatedFiles.first else {
            throw CodegenError.unexpectedGeneratedFileCount(
                generatedFiles.count
            )
        }

        return try String(contentsOf: generatedFile, encoding: .utf8)
    }

    private static func writeIfChanged(
        _ source: String,
        to output: URL
    ) throws {
        let data = Data(source.utf8)
        if let existingData = try? Data(contentsOf: output),
           existingData == data {
            return
        }

        try FileManager.default.createDirectory(
            at: output.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try data.write(to: output, options: .atomic)
    }
}

private struct Arguments {
    let input: URL?
    let namespace: String
    let output: URL

    init(_ rawArguments: [String]) throws {
        var values = Array(rawArguments.dropFirst())
        let input = Self.extract("--input", from: &values)

        guard let namespace = Self.extract("--namespace", from: &values),
              let output = Self.extract("--output", from: &values),
              values.isEmpty,
              namespace.range(
                  of: "^[A-Z][A-Za-z0-9]*$",
                  options: .regularExpression
              ) != nil else {
            throw CodegenError.invalidArguments
        }

        self.input = input.map(URL.init(fileURLWithPath:))
        self.namespace = namespace
        self.output = URL(fileURLWithPath: output)
    }

    private static func extract(
        _ option: String,
        from arguments: inout [String]
    ) -> String? {
        guard let optionIndex = arguments.firstIndex(of: option),
              arguments.indices.contains(optionIndex + 1) else {
            return nil
        }

        arguments.remove(at: optionIndex)
        return arguments.remove(at: optionIndex)
    }
}

private enum CodegenError: Error, CustomStringConvertible {
    case invalidArguments
    case unexpectedGeneratedFileCount(Int)
    case xcstringstoolFailed(status: Int32)

    var description: String {
        switch self {
        case .invalidArguments:
            "usage: SwiftLocalizedGenerator [--input <catalog>] "
                + "--namespace <name> --output <swift>"

        case let .unexpectedGeneratedFileCount(count):
            "xcstringstool generated \(count) Swift files instead of one"

        case let .xcstringstoolFailed(status):
            "xcstringstool failed with status \(status)"
        }
    }
}
#else
@main
struct SwiftLocalizedGenerator {
    static func main() {
        fatalError("SwiftLocalizedGenerator is a macOS build tool")
    }
}
#endif
